FROM alpine:3.8
MAINTAINER mariana.sequeira@celfocus.com

RUN apk -U add git
RUN git config --global user.email "mariana.sequeira@celfocus.com" && git config --global user.name "mariana.sequeira@celfocus.com"
